import { defineConfig } from 'vitepress'
import { readFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

// ── Load cached git info ──────────────────────────────────────────
const gitInfoPath = resolve(__dirname, 'cache/git-info.json')
let gitInfo = {}
try {
  if (existsSync(gitInfoPath)) {
    gitInfo = JSON.parse(readFileSync(gitInfoPath, 'utf-8'))
  }
} catch { /* silent */ }

// ── Load cached sidebar (auto-generated by generate-sidebar.mjs) ──
const sidebarPath = resolve(__dirname, 'cache/sidebar.json')
let sidebarData = {}
try {
  if (existsSync(sidebarPath)) {
    sidebarData = JSON.parse(readFileSync(sidebarPath, 'utf-8'))
  }
} catch { /* silent */ }

const zhSidebar = sidebarData['/guide/'] ? { '/guide/': sidebarData['/guide/'] } : {}
const enSidebar = sidebarData['/en/guide/'] ? { '/en/guide/': sidebarData['/en/guide/'] } : {}

// ── Nav ─────────────────────────────────────────────────────────────
const zhNav = [{ text: '文档总览', link: '/guide/other-docs/getting-started', activeMatch: '/guide/' }]
const enNav = [{ text: 'Docs', link: '/en/guide/other-docs/getting-started', activeMatch: '/en/' }]

// ── VitePress config ──────────────────────────────────────────────
export default defineConfig({
  lang: 'zh-CN',
  title: 'HyperSynapse Network Docs',
  description: 'HyperSynapse Network 技术文档',
  appearance: 'dark',

  head: [
    ['link', { rel: 'icon', href: '/logo.svg' }],
  ],

  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'HSN Docs',

    socialLinks: [
      { icon: 'github', link: 'https://github.com/HyperSynapseNetwork' },
    ],

    footer: {
      message: 'Built with VitePress',
      copyright: `Copyright © ${new Date().getFullYear()} HyperSynapse Network`,
    },

    search: {
      provider: 'local',
    },
  },

  // ── i18n locales ─────────────────────────────────────────────────
  locales: {
    root: {
      label: '中文',
      lang: 'zh-CN',
      title: 'HyperSynapse Network Docs',
      description: 'HyperSynapse Network 技术文档',
      themeConfig: {
        nav: zhNav,
        sidebar: zhSidebar,
      },
    },
    en: {
      label: 'English',
      lang: 'en',
      title: 'HyperSynapse Network Docs',
      description: 'Documentation for HyperSynapse Network',
      themeConfig: {
        nav: enNav,
        sidebar: enSidebar,
      },
    },
  },

  // ── Inject git info into every page frontmatter ────────────────
  transformPageData(pageData) {
    const relativePath = pageData.relativePath
    const info = gitInfo[relativePath]
    if (info) {
      pageData.frontmatter.lastModifier = info.author
      pageData.frontmatter.lastModTime = info.date
    }
    return pageData
  },

  // ── Sitemap ────────────────────────────────────────────────────
  sitemap: {
    hostname: 'https://docs.htadiy.com',
  },

  lastUpdated: false, // we use our own GitMeta component instead
})
